version: "3.7"
services:
  app:
    build: .
    ports:
      - "5501:5501"
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secure
      MYSQL_DATABASE: employee_management
    ports:
      - "3306:3306"

